name: Insights

on:
  push:
    branches:
      - main

jobs:
  build_app:
    name: Build the App and the Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2

      - name: Build the server and client
        run: deno task build

      - name: Build the Docker image
        working-directory: server
        run: docker build -t insights:latest .
